name: diresto
description: "Diresto Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"
dependencies:
  android_alarm_manager_plus: ^4.0.6
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.1
  get_it: ^7.7.0
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  lottie: ^3.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  readmore: ^2.2.0
  rxdart: ^0.27.7
  sqflite: ^2.3.1

dev_dependencies:
  flutter_lints: ^2.0.3
  bloc_test: ^9.1.7
  build_runner: ^2.0.4
  mockito: ^5.4.2
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/empty_box.png
    - assets/resto.json
    - assets/halal.png
    - assets/error_data.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
