// Mocks generated by Mockito 5.4.4 from annotations
// in diresto/test/bloc/detail_restaurant_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:diresto/data/model/detail_restaurant.dart' as _i7;
import 'package:diresto/domain/repositories/app_repository.dart' as _i2;
import 'package:diresto/domain/usecase/get_detail_restaurant.dart' as _i4;
import 'package:diresto/utils/failure.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppRepository_0 extends _i1.SmartFake implements _i2.AppRepository {
  _FakeAppRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetDetailRestaurant].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDetailRestaurant extends _i1.Mock
    implements _i4.GetDetailRestaurant {
  MockGetDetailRestaurant() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppRepository get appRepository => (super.noSuchMethod(
        Invocation.getter(#appRepository),
        returnValue: _FakeAppRepository_0(
          this,
          Invocation.getter(#appRepository),
        ),
      ) as _i2.AppRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.DetailRestaurant>> execute(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.DetailRestaurant>>.value(
                _FakeEither_1<_i6.Failure, _i7.DetailRestaurant>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.DetailRestaurant>>);
}
